server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

  #aliyun:
    #oss:
    #endpoint: #注释
    #key-id: #阿里云申请
    #bucket-name: #注释
    #key-secret: #阿里云申请
